import Head from "next/head";
import Image from "next/image";
import SideBar from "../components/SideBar";
import styled from "styled-components";
import { useState } from "react";

export default function Home() {

  const [innerWidth, setInnerWidth] = useState(window.innerWidth);
  const [mobile, setMobile] = useState(false);
  window.addEventListener("resize", () => {
    setInnerWidth(window.innerWidth);
  });

  if (innerWidth <= 579) {
    if (!mobile) setMobile(true);
  } else {
    if (mobile) setMobile(false);
  }
  return (
    <Container>
      <Head>
        <title>Whatsapp 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://logo-logos.com/2016/10/WhatsApp_logo_icon.png"
        />
      </Head>

      <SideBar mobile={mobile} />
      {!mobile && (
        <StartChat>
          <TextContainer>Start Chatting...</TextContainer>
        </StartChat>
      )}
    </Container>
  );
}

const Container = styled.div`
  display: flex;
`;

const StartChat = styled.div`
  flex: 1;
  overflow: hidden;
  width: 100%;
  height: 100vh;
`;

const TextContainer = styled.div`
  display: flex;
  align-items: center;
  height: 100%;
  justify-content: center;
  text-transform: uppercase;
  background-color: whitesmoke;
`;
